final List<String> suggestions = [
  "Wallpapers",
  "3D Renders",
  "Travel",
  "Nature",
  "Street Photography",
  "Experimental",
  "Textures & Patterns",
  "Animals",
  "Architecture & Interiors",
  "Fashion & Beauty",
  "Film",
  "Food & Drink",
  "People",
  "Spirituality",
  "Business & Work",
  "Athletics",
  "Health & Wellness",
  "Current Events",
  "Arts & Culture",
];
